config/routes.rb
Rails.application.routes.draw do
  root 'notes#index' 
  resources :notes  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  validates :title, presence: true, uniqueness: { case_sensitive: false }

  def self.search_by_title(keywords)
    keywords.split.reduce(self) do |acc, word|
      acc.where "title LIKE ? ESCAPE '\\'", "%#{escape_sql_pattern word}%"
    end
  end

  private

  def self.escape_sql_pattern(pattern)
    pattern.gsub(/[%_\\]/, '\\\\\\&')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[show edit update destroy]

  def index
    @notes = Note.all

    filters = params[:filters]&.to_unsafe_h&.symbolize_keys
    if filters && filters[:search].present?
      # Buscar en título y contenido
      @notes = @notes.where("title LIKE ? OR body LIKE ?", "%#{filters[:search]}%", "%#{filters[:search]}%")
    end

    # Ordenar las notas según el parámetro de orden
    if filters && filters[:order].present?
      case filters[:order]
      when 'desc_date'
        @notes = @notes.order(created_at: :desc)  # Más reciente a más antiguo
      when 'asc_date'
        @notes = @notes.order(created_at: :asc)   # Más antiguo a más reciente
      when 'asc_alpha'
        @notes = @notes.order(:title)             # Alfabético A-Z
      when 'desc_alpha'
        @notes = @notes.order(title: :desc)       # Alfabético Z-A
      else
        @notes = @notes.order(created_at: :desc)  # Si no se pasa un parámetro válido, ordenamos por fecha por defecto
      end
    else
      # Orden por defecto: por fecha (más reciente a más antiguo)
      @notes = @notes.order(created_at: :desc)
    end
  end

  def show
  end

  def new
    @note = Note.new
  end

  def edit
  end

  def create
    @note = Note.new(note_params)
  
    respond_to do |format|
      if @note.save
        format.html { redirect_to note_url(@note), notice: "Note successfully created." }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to note_url(@note), notice: "Note successfully updated." }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end
  

  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: "Note was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_as_localtime(datetime, format = '')
    format = "%d/%b/%Y, %H:%M:%S" unless format.present?
    datetime.localtime.strftime format
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My note collection</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style>
      /* Estilos para el modo oscuro */
      body.dark-mode {
        background-color: #121212;
        color: #e0e0e0;
      }
      .navbar-fixed.dark-mode {
        background-color: #333;
      }
      .navbar-fixed.dark-mode .nav-wrapper {
        background-color: #333;
      }
      .brand-logo.center.dark-mode {
        color: #fff;
      }
      .btn-dark-mode {
        background-color: #333;
        color: white;
      }
    </style>
  </head>

  <body>
    <div class="navbar-fixed">
      <nav>
        <div class="nav-wrapper">
          <%= link_to notes_path, class: 'brand-logo center' do %>
            My note collection
          <% end %>

          <!-- Botón para cambiar a modo oscuro -->
          <a href="javascript:void(0);" class="btn btn-small waves-effect waves-light btn-dark-mode right" id="dark-mode-toggle"   style="border-radius: 50%; background-color: #333; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.3); transition: background-color 0.3s, transform 0.3s;">
            change theme          
          </a>
        </div>
      </nav>
    </div>

    <div class="container">
      <%= yield %>
    </div>

    <script>
      // Cambiar entre modo oscuro y claro
      const darkModeToggle = document.getElementById('dark-mode-toggle');

      // Verificar el estado del modo oscuro guardado en localStorage
      if (localStorage.getItem('darkMode') === 'enabled') {
        document.body.classList.add('dark-mode');
      }

      darkModeToggle.addEventListener('click', () => {
        document.body.classList.toggle('dark-mode');
        
        // Guardar el estado en localStorage
        if (document.body.classList.contains('dark-mode')) {
          localStorage.setItem('darkMode', 'enabled');
        } else {
          localStorage.setItem('darkMode', 'disabled');
        }
      });
    </script>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: note) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h5><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h5>

      <ul>
        <% note.errors.each do |error| %>
          <li>&bull; <%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row" style="margin-top: 7mm">
    <div class="input-field col s12">
      <%= form.text_field :title, autofocus: true %>
      <%= form.label :title %>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s12">
      <%= form.text_area :body, class: 'materialize-textarea' %>
      <%= form.label :body %>
    </div>
  </div>

  <div class="row">
    <div class="col s12 right-align">
      <button class="btn-flat waves-effect waves-light" type="submit">
        <%= material_icon.send %>
      </button>
    </div>
  </div>
<% end %>

app/views/notes/edit.html.erb
<%= render 'form', note: @note %>

app/views/notes/index.html.erb
<div class="row">
  <%= form_for :filters, html: { class: 'input-field col s12 filters-form' }, method: 'get' do |f| %>
    <div class="filters-container" style="display: flex; align-items: center; gap: 10px;">

    <div class="input-field" style="flex: 2;">
        <%= material_icon.search.css_class('prefix') %>
        <%= f.text_field :search, autofocus: true, placeholder: 'Search', value: params.dig(:filters, :search), class: 'validate' %>
      </div>

      <div class="input-field" style="flex: 1;">
        <%= f.select :order, [['Newest to oldest', 'desc_date'], 
                              ['Older to newer', 'asc_date'], 
                              ['Alphabetical A-Z', 'asc_alpha'], 
                              ['Alphabetical Z-A', 'desc_alpha']],
                     { selected: params.dig(:filters, :order) }, 
                     { class: 'browser-default' } %>
      </div>
      <div>
        <%= f.submit 'Apply', class: 'btn' %>
      </div>
    </div>
  <% end %>
</div>



  <% # Agrupar las notas por mes %>
  <% @notes.group_by { |note| note.created_at.strftime('%B %Y') }.each do |month, notes| %>
    <div class="col s12">
      <h5 class="month-header"><%= month %></h5>
    </div>

    <% notes.each do |note| %>
      <%= link_to note_path(note) do %>
        <div class="col s12">
          <div class="card">
            <div class="card-content black-text">
              <span class="card-title">
                <%= note.title %>
                <span class="right" style="font-size: 60%; position: absolute; top: -5px; right: 5px;">
                  <%= format_as_localtime note.created_at %>
                </span>
              </span>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

<div class="fixed-action-btn">
  <%= link_to new_note_path, title: 'New note', class: 'btn-floating btn-large pulse', data: { tooltip: 'New note' } do %>
    <%= material_icon.add %>
  <% end %>
</div>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.tooltipped');
    var instances = M.Tooltip.init(elems);

    const select = document.querySelector('[name="filters[order]"]');
    if (select) {
      const savedOrder = localStorage.getItem('notesOrder');
      if (savedOrder) select.value = savedOrder;

      select.addEventListener('change', function() {
        localStorage.setItem('notesOrder', select.value);
      });
    }
  });
</script>

app/views/notes/new.html.erb
<%= render 'form', note: @note %>

<% if @note.errors.any? %>
  <div class="card-panel red lighten-4">
    <ul>
      <% @note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/notes/show.html.erb
<head>
  <style>
    notice, .card-content p {
      word-wrap: break-word; 
      overflow-wrap: break-word; 
      white-space: pre-wrap; 
      word-break: break-word; 
    }

    notice {
      max-height: 200px; 
      overflow-y: auto;
    }
  </style>
</head>

<body>
  <p id="notice"><%= notice %></p>

  <div class="row">
    <div class="col s12">
      <div class="card">
        <div class="card-content">
          <span class="card-title">
            <%= @note.title %>
            <span class="right" style="font-size: 50%">
              <%= format_as_localtime @note.created_at %>
            </span>
          </span>
          <p style="white-space: pre-line"><%= @note.body %></p>
        </div>
        <div class="card-action">
          <%= link_to @note, title: 'Delete', method: :delete, data: { confirm: 'Are you sure?' }, class: 'black-text' do %>
            <%= material_icon.delete %>
          <% end %>

          <%= link_to edit_note_path(@note), title: 'Edit', class: 'black-text right' do %>
            <%= material_icon.mode_edit %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</body>